### ISSUE TITLE
Error: Cannot find module 'cls-hooked'

### ISSUE THREAD

**Issue by yoshig** [blankstar85/sequelize-central-log#5]
The latest pushes seems to have created a new error:

```
14:58:32  Error: Cannot find module 'cls-hooked'
14:58:32  Require stack:
14:58:32  - /srv/backend/node_modules/sequelize-central-log/lib/index.js
14:58:32  - /srv/backend/api/v1/models/index.ts
14:58:32  - /srv/backend/migrator.ts
14:58:32      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
14:58:32      at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/srv/backend/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
14:58:32      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
14:58:32      at Module.require (node:internal/modules/cjs/loader:1005:19)
14:58:32      at require (node:internal/modules/cjs/helpers:102:18)
14:58:32      at Object.<anonymous> (/srv/backend/node_modules/sequelize-central-log/src/index.ts:10:1)
14:58:32      at Module._compile (node:internal/modules/cjs/loader:1103:14)
14:58:32      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
14:58:32      at Module.load (node:internal/modules/cjs/loader:981:32)
14:58:32      at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
14:58:32    code: 'MODULE_NOT_FOUND',
14:58:32    requireStack: [
14:58:32      '/srv/backend/node_modules/sequelize-central-log/lib/index.js',
14:58:32      '/srv/backend/api/v1/models/index.ts',
14:58:32      '/srv/backend/migrator.ts'
14:58:32    ]
14:58:32  }
```

**Comment by blankstar85** [comment]
I updated the package for the peer-dependencies, This requires cls-hooked, commonly used in sequelize for transactions.
